# Generated by Django 3.1.3 on 2020-11-26 10:09

from django.db import migrations, models
import product_api.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(default=None, verbose_name='Date updated')),
                ('logo', models.ImageField(upload_to=product_api.models.upload_location)),
                ('rotate_duration', models.FloatField()),
            ],
        ),
    ]
